---
prestashop_version: 1.7.7.1
prestashop_url_download: "https://github.com/PrestaShop/PrestaShop/archive/{{ prestashop_version }}.tar.gz"

prestashop_root_path: "/var/www/prestashop_domain"

prestashop_domain: "prestashop.test"
prestashop_db_create: 1
prestashop_db_clear: 1
prestashop_db_server: "localhost"
prestashop_db_name: "prestashop"
prestashop_db_user: "root"
prestashop_db_password: "test123"
prestashop_db_engine: "InnoDB"
prestashop_db_prefix: "ps_"
prestashop_language: "fr"
prestashop_country: "fr"
prestashop_timezone: "Europe/Paris"
prestashop_newsletter: 0

prestashop_firstname: "PrestaShop"
prestashop_lastname: "Developer"
prestashop_password: "p_prestashop"
prestashop_email: "dev@prestashop.com"

prestashop_admin_folder_name: "adminpr-ort_2020-2021"
prestashop_check_file_name: "prestashop-installed.txt"
...